@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FAS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include FAS/aws.puml
!include DEVICONS/google_cloud_platform.puml

LAYOUT_TOP_DOWN()

title Context Diagram

Person(consumer, "An infrastructure consumer")
Person(producer, "An infrastructure producer")

System(northstar, "Northstar", "Orchestrates cloud infrastructure")

System_Ext(aws, "Amazon Web Services", $sprite="aws")
System_Ext(gcp, "Google Cloud Platform", $sprite="google_cloud_platform")
System_Ext(cloud, "Another Cloud")

Rel_L(consumer, northstar, "Provision infrastructure abstractions using")
Rel_R(producer, northstar, "Build infrastructure abstractions using")

Rel(northstar, aws, "Create infrastructure on")
Rel(northstar, gcp, "Create infrastructure on")
Rel(northstar, cloud, "Create infrastructure on")

@enduml