@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/rust.puml

LAYOUT_TOP_DOWN()

title Container diagram for Internet Banking System

Person(user, "Kubernetes consumer")

System_Ext(cloud, "Cloud Provider", "Provide managed cloud services")

System_Boundary(northstar, "Northstar") {
    Container(cli, "Command Line Interface", "Rust", "Provides all Northstar functionnality to customer via their terminal", "rust")
    Container(spa, "Single Page Application", "Javascript, React", "Provides simplified UI to maintain clusters", "react")
    Container(api, "API", "Rust, Actix", "Provides Northstar functionality via a JSON/GRPC API", "rust")
}

Rel(user, cli, "Views and create clusters using")
Rel(user, spa, "Views and create clusters using", "https")

Rel(cli, api, "Makes api calls to", "JSON/HTTPS")
Rel(spa, api, "Makes api calls to", "JSON/HTTPS")

Rel(api, cloud, "Provision clusters using", "https")

@enduml