@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Kubernetes consumer")
Person(operator, "Kubernetes Operator")

System(northstar, "Northstar", "Allow users to provision and orchestrate customized kubernetes clusters")
System_Ext(cloud, "Cloud Provider", "Provide managed cloud services")

Rel(user, northstar, "Create and list clusters using")
Rel(operator, northstar, "Create pre-configured clusters templates using")
Rel(northstar, cloud, "Create servers and orchestrate clusters using")

@enduml